/*Tengo como máximo 8000 euros y quiero una bicicleta que sea electrica */
db.bicicletas.find( { $and: [ { preciobicicleta: { $lt: 8000 } }, { electrica:true } ] } )
/*{ "_id" : ObjectId("61913b10641cfe445e22ee87"), "marca" : "Moustache", "modelo" : "Samedi", "preciobicicleta" : 7800, "cuadro" : { "aluminio" : "Fourstroke 01", "medida" : "M-54" }, "ruedas" : { "tipo" : "CROSSMAX PRO", "cubiertas" : { "tipo" : "Maxxis Assegai", "medida" : { "h" : 29, "w" : 2.5 } } }, "componentes" : [ "horquilla", "frenos", "manillar", "juego de dirección", "sillín", "tija de sillin", "bielas", "palancasdecambios", "discodefreno", "potencia" ], "desviadores" : { "delantero" : "Shimano, Altus", "trasero" : "Shimano Dura-Ace" }, "sillín" : { "tipo" : "Moustache, Performance", "Características" : [ "Rieles de carbono", "Con montura directa" ] }, "cassette" : [ "SRAM XG", "12 Speed" ], "date" : ISODate("1970-01-01T00:00:00Z"), "montaña" : false, "carretera" : false, "electrica" : true } */

/*La semana pasada vi una bicicleta donde tenia un cuadro de carbono Addict Gravel y una medida XS-49 pero no me acuerdo de la marca y quiero saberlo*/
db.bicicletas.find( { $and: [ { "cuadro.carbono": "Addict Gravel Disc HMX" }, { "cuadro.medida": "XS-49" } ] } )
/*{ "_id" : ObjectId("619171cae438ab51bc8c4602"), "marca" : "Scott", "modelo" : "Addict Gravel Tuned", "preciobicicleta" : 8700, "cuadro" : { "carbono" : "Addict Gravel Disc HMX", "medida" : "XS-49" }, "ruedas" : { "tipo" : "DT Swiss", "cubiertas" : { "tipo" : "Schwalbe", "medida" : { "h" : 700, "w" : 45 } } }, "componentes" : [ "horquilla", "frenos", "manillar", "juego de dirección", "sillín", "tija de sillin", "bielas", "palancasdecambios", "discodefreno", "potencia" ], "desviadores" : [ { "tipo" : "SRAM RED eTap AXS", "pesomedio" : 280 }, { "tipo" : "Shimano, XTR", "pesomedio" : 237 } ], "sillín" : { "tipo" : "Syncros", "Características" : [ "Rieles de carbono", "Con montura directa" ] }, "cassette" : [ "SRAM FORCE", "12 Speed" ], "date" : ISODate("1970-01-01T00:00:00Z"), "montaña" : true, "carretera" : true, "electrica" : false } */

/*A mi no me gustan las bicicletas electricas y por eso solo utilizo las de montaña o la de carretera */
db.bicicletas.find( { electrica: { $not: { $eq: true } } } )
db.bicicletas.find( { electrica: { $ne: true } } )
/*{ "_id" : ObjectId("619171cae438ab51bc8c4602"), "marca" : "Scott", "modelo" : "Addict Gravel Tuned", "preciobicicleta" : 8700, "cuadro" : { "carbono" : "Addict Gravel Disc HMX", "medida" : "XS-49" }, "ruedas" : { "tipo" : "DT Swiss", "cubiertas" : { "tipo" : "Schwalbe", "medida" : { "h" : 700, "w" : 45 } } }, "componentes" : [ "horquilla", "frenos", "manillar", "juego de dirección", "sillín", "tija de sillin", "bielas", "palancasdecambios", "discodefreno", "potencia" ], "desviadores" : [ { "tipo" : "SRAM RED eTap AXS", "pesomedio" : 280 }, { "tipo" : "Shimano, XTR", "pesomedio" : 237 } ], "sillín" : { "tipo" : "Syncros", "Características" : [ "Rieles de carbono", "Con montura directa" ] }, "cassette" : [ "SRAM FORCE", "12 Speed" ], "date" : ISODate("1970-01-01T00:00:00Z"), "montaña" : true, "carretera" : true, "electrica" : false }
{ "_id" : ObjectId("619171cae438ab51bc8c4603"), "marca" : "BMC", "modelo" : "Fourstroke 01 LT ONE", "preciobicicleta" : 8000, "cuadro" : { "carbono" : "Fourstroke 01", "medida" : "S-52" }, "ruedas" : { "tipo" : "CROSSMAX PRO", "cubiertas" : { "tipo" : "Vittoria Barzo", "medida" : { "h" : 29, "w" : 2.5 } } }, "componentes" : [ "horquilla", "frenos", "manillar", "juego de dirección", "sillín", "tija de sillin", "bielas", "palancasdecambios", "discodefreno", "potencia" ], "desviadores" : [ { "tipo" : "Shimano, Altus", "peso" : 295 }, { "Tipo" : "Sram XX1", "pesomedio" : 355 } ], "sillín" : { "tipo" : "Fizik", "Características" : [ "Rieles de carbono", "Con montura directa" ] }, "cassette" : [ "SRAM XG", "12 Speed" ], "date" : ISODate("1970-01-01T00:00:00Z"), "montaña" : true, "carretera" : false, "electrica" : false }
{ "_id" : ObjectId("619171cae438ab51bc8c4605"), "marca" : "Cube", "modelo" : "HVRT CF Zero", "preciobicicleta" : 6500, "cuadro" : { "carbono" : "HVRT Aero Design", "medida" : "L-56" }, "ruedas" : { "tipo" : "Rondo X HUNT", "cubiertas" : { "tipo" : "Continental", "medida" : { "h" : 29, "w" : 2.5 } } }, "componentes" : [ "horquilla", "frenos", "manillar", "juego de dirección", "sillín", "tija de sillin", "bielas", "palancasdecambios", "discodefreno", "potencia" ], "desviadores" : [ { "tipo" : "Shimano Dura-Ace", "pesomedio" : 85 }, { "Tipo" : "Sram XX1", "pesomedio" : 355 } ], "sillín" : { "tipo" : "ALMS CF", "Características" : [ "Rieles de carbono", "Con montura directa" ] }, "cassette" : [ "SRAM XG", "12 Speed" ], "date" : ISODate("1970-01-01T00:00:00Z"), "montaña" : false, "carretera" : true, "electrica" : false }
{ "_id" : ObjectId("619171cae438ab51bc8c4606"), "marca" : "Trek", "modelo" : "Slash 9.8 GX", "preciobicicleta" : 7000, "cuadro" : { "carbono" : "OCLV Mountain", "medida" : "XS-49" }, "ruedas" : { "tipo" : "Bontrager", "cubiertas" : { "tipo" : "Bontrager SE5", "medida" : { "h" : 700, "w" : 45 } } }, "componentes" : [ "horquilla", "frenos", "manillar", "juego de dirección", "sillín", "tija de sillin", "bielas", "palancasdecambios", "discodefreno", "potencia" ], "desviadores" : [ { "tipo" : "Shimano Dura-Ace", "pesomedio" : 85 }, { "Tipo" : "Sram XX1", "pesomedio" : 355 } ], "sillín" : { "tipo" : "Bontrager Arvada", "Características" : [ "Rieles de carbono", "Con montura directa" ] }, "cassette" : [ "SRAM XG", "12 Speed" ], "date" : ISODate("1970-01-01T00:00:00Z"), "montaña" : true, "carretera" : false, "electrica" : false }
{ "_id" : ObjectId("619171cae438ab51bc8c4607"), "marca" : "Giant", "modelo" : "PROPEL ADVANCED PRO", "preciobicicleta" : 6000, "cuadro" : { "carbono" : "Advanced-Grade Composite", "medida" : "XL-58" }, "ruedas" : { "tipo" : "Giant SLR 1", "cubiertas" : { "tipo" : "CADEX Race 25", "medida" : { "h" : 700, "w" : 25 } } }, "componentes" : [ "horquilla", "frenos", "manillar", "juego de dirección", "sillín", "tija de sillin", "bielas", "palancasdecambios", "discodefreno", "potencia" ], "desviadores" : [ { "tipo" : "Shimano, Altus", "pesomedio" : 295 }, { "Tipo" : "SRAM Force", "pesomedio" : 322 } ], "sillín" : { "tipo" : "Giant Fleet SL", "Características" : [ "Rieles de carbono", "Con montura directa" ] }, "cassette" : [ "SRAM XG", "12 Speed" ], "date" : ISODate("1970-01-01T00:00:00Z"), "montaña" : false, "carretera" : true, "electrica" : false }
{ "_id" : ObjectId("619171cae438ab51bc8c4608"), "marca" : "Cervélo", "modelo" : "Aspero-5", "preciobicicleta" : 8000, "cuadro" : { "carbono" : "Gravel Carbon", "medida" : "XL-58" }, "ruedas" : { "tipo" : "Reserve Carbon", "cubiertas" : { "tipo" : "Panaracer Grave", "medida" : { "h" : 700, "w" : 38 } } }, "componentes" : [ "horquilla", "frenos", "manillar", "juego de dirección", "sillín", "tija de sillin", "bielas", "palancasdecambios", "discodefreno", "potencia" ], "desviadores" : [ { "tipo" : "Shimano GRX", "pesomedio" : 96 }, { "Tipo" : "SRAM Force", "pesomedio" : 322 } ], "sillín" : { "tipo" : "Prologo Dimension", "Características" : [ "Rieles de carbono", "Con montura directa" ] }, "cassette" : [ "SRAM Force", "12 Speed" ], "date" : ISODate("1970-01-01T00:00:00Z"), "montaña" : true, "carretera" : true, "electrica" : false } */

/*Me gustaría ver las bicicletas que valgan 7500 o menos de 7500 y la medida del cuadro sea XS-49 */
db.bicicletas.find ({$and:[{"cuadro.talla":["XS-49"]},{"preciobicicleta":{$lte:6000}}]}).pretty()

/*Estoy buscando una bicicleta que valga menos de 8000€ y me gustaria que tuviera cuadro de carbono Gravel */
db.bicicletas.find ({$and:[{preciobicicleta:{$lt:8000}}, {"cuadro.carbono": {$eq:"Gravel"}}]}).pretty()

/*Quiero ver las bicicletas que los desviadores tengan un peso medio de 355g y quiero que sea Sram */
db.bicicletas.find({$and:[{"desviadores.pesomedio":{$size:355}}, {"desviadores.tipo":{$eq:"Sram XX1"}}]}).pretty()

/*Buscar la opcion de una bicicleta de la marca Trek sea de montaña*/
db.bicicletas.find({"marca.Trek":{$exists:true}}).pretty()

/*Quiero ir a todobici para ver bicicletas modernas del año 2020 y tengo 12000€, entonces tengo o para una bicicleta más cara o para dos bicicletas más baratas y me tengo que decidir entre una o otra pro antes quiero saber cuantas bicicletas hay por 6000€ y cuantas x 8000€*/
db.bicicletas.find( { $or: [ {date:( { $gte: new Date ("2020-01-01") }), preciobicicleta: 8000},{date:( { $gte: new Date ("2020-01-01") }), preciobicicleta: 6000}]}).pretty()
db.bicicletas.find( { $and: [ { date:new Date( { $gte: "2020-01-01" } )}, { precioentrada: 8000 } ] } )
db.bicicletas.find( { $and: [ { date:new Date( { $gte: "2020-01-01" } )}, { precioentrada: 6000 } ] } )
/*"_id" : ObjectId("61918d06de4f3d452a75e748"),"marca" : "Scott","modelo" : "Addict Gravel Tuned","preciobicicleta" : 8000,"cuadro" : {        "carbono" : "Addict Gravel Disc HMX",        "talla" : "XS-49"}, "ruedas" : {               "tipo" : "DT Swiss", "cubiertas" : {        "tipo" : "Schwalbe",        "medida" : {                "h" : 700,                "w" : 45        } }}, "componentes" : [         "horquilla",         "frenos",         "manillar",         "juego de dirección",         "sillín",         "tija de sillin",         "bielas",         "palancasdecambios",  "discodefreno","potencia"],"desviadores" : [        {                "tipo" : "SRAM RED eTap AXS",                "pesomedio" : 280        },        {                "tipo" : "Shimano, XTR",                "pesomedio" : 237         } ], "sillín" : {        "tipo" : "Syncros",        "Características" : [                "Rieles de carbono",                "Con montura directa"        ]}, "cassette" : [        "SRAM FORCE",        "12 Speed"  ], "date" : ISODate("2021-01-06T23:00:00Z"), "montaña" : true, "carretera" : true, "electrica" : false}{
"_id" : ObjectId("61918d06de4f3d452a75e74a"),     "marca" : "Moustache",     "modelo" : "Samedi",     "preciobicicleta" : 8000,     "cuadro" : {             "aluminio" : "Fourstroke 01             "talla" : "M-54"      },      "ruedas" : {              "tipo" : "CROSSMAX PRO",             "cubiertas" : {                     "tipo" : "Maxxis Assegai","medida" :                               "h" : 29,"w" : 2.5 } } },      "componentes" : [                "horquilla",            "frenos",              "manillar",              "juego de dirección",              "sillín",                "tija de sillin",                "bielas",                "palancasdecambios",                "discodefreno",               "potencia"       ],        "desviadores" : { "delantero" : "Shimano, Altus", "trasero" : "Shimano Dura-Ace" },"sillín" : { "tipo" : "Moustache, Performance","Características" : ["Rieles de carbono","Con montura directa" ]},"cassette" : ["SRAM XG","12 Speed"],"date" : ISODate("2020-12-31T23:00:00Z"),"montaña" : false,"carretera" : false,"electrica" : true */

/*me gustaría comprarme una bicicleta que valga 6000 y que tenga los desviadores un peso medio de 85 , 355*/
db.bicicletas.find({$and:[{"precio":{$gte:6000}},{"desviadores.pesomedio":{$in:[85, 355]}}]}).pretty()
